### ISSUE TITLE
Change github repo and name

### ISSUE THREAD

**Issue by jersoncarin** [WarenGonzaga/awesome-css-text-portrait#1]
Hi, Master can you change the github repo of jersoncarin-dev

Repo: https://github.com/jersoncarin/css-portrait-image-generator
Name: https://github.com/jersoncarin (jersoncarin)

Thanks

**Comment by warengonzaga** [comment]
got it, thanks!

**Comment by warengonzaga** [comment]
Updated! @jersoncarin 👌
