### ISSUE TITLE
add CSS Text Portrait Generator

### ISSUE THREAD

**Issue by binarykore** [WarenGonzaga/awesome-css-text-portrait#6]
Sir Waren, Ito na yung Contribution ko. Salamatsu!

Cheers,
Jaede Sy

**Comment by warengonzaga** [comment]
@binarykorra can you please use English as this repo is international.

**Comment by binarykore** [comment]
Okay. Haha.

So this is my Contribution in your Repo. Tengchu!

Cheers,
Jaede Sy

**Comment by warengonzaga** [comment]
Awesome! @binarykorra I'll review again your PR.

**Comment by warengonzaga** [comment]
All good @binarykorra! Thanks for the contribution!
